### ISSUE TITLE
Logging gets stuck on getting started page in prod-preview

### ISSUE THREAD

**Issue by hectorj2f** [fabric8-ui/fabric8-planner#1910]
When login in prod-preview with the github login provider, I cannot go further of this web page. I select Github + connect account and I am back to the same page.
![screen shot 2017-05-19 at 12 31 24 pm](https://cloud.githubusercontent.com/assets/3602792/26244553/61251a0e-3c90-11e7-9ba3-fa3b5a4dfef4.png)

**Comment by alexeykazakov** [comment]
Make sure you don't have this GitHub account already linked to another user.

**Comment by hectorj2f** [comment]
@alexeykazakov Yes, I do have it. Should I remove that account ? How to proceed ?

**Comment by hectorj2f** [comment]
ping @alexeykazakov

**Comment by alexeykazakov** [comment]
@hectorj2f we do not currently support multiple accounts which linked to the same GitHub account. This is a KC limitation.
First at all we should let the user know if it's the case instead of silently ignoring it - https://github.com/almighty/almighty-core/issues/1350
Then we need to figure out if we actually can solve this on SSO level and make it possible to connect the same GitHub to different osio users.
For now, just go to KC and remove the GitHub link from the existing account so you can re-link it in your second account.

**Comment by debloper** [comment]
Steps to functionally (i.e. without proper UX feedback) resolve this issue for the user:

* Go to GitHub account's settings page and revoke openshit.io as authorized OAuth app
* Try to connect GitHub again (on the UI it'll still fail/loopback)
* Check GitHub if the new OAuth app has been added
* If on GitHub settings it's updated then the connection has been established
* Visit `/_home` and your problem should go away, and app should work as intended

**Comment by hectorj2f** [comment]
That has been solved. Closing this issue!
